steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/lerietmall/lerietmall_apirest:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/lerietmall/lerietmall_apirest:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'lerietmallapirest', '--region=us-east1', '--platform=managed', 'gcr.io/lerietmall/lerietmall_apirest:$SHORT_SHA']
